### PR TITLE
Testing To Do list: part 1

### PR DESCRIPTION
**Pull request by Fayob**
## Testing add task and remove task

### CODE REVIEW

**Review by ichala — CHANGES_REQUESTED** [review]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

🛑 You Already had the first review in this [PR](https://github.com/Okechukwu-muokwugwo/ToDoList/pull/6), kindly try to implement the changes requested in the first submitted repo and to be more specific this [Pull Request](https://github.com/Okechukwu-muokwugwo/ToDoList/pull/6) 🛑

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Fayob** [comment]
Hi @ichala, please I think we are doing group project and the previous code as not been approved yet and we can use anyone's repository to submit the first task.

**Comment by ichala** [comment]
Hello, @Fayob I'm sorry I can't proceed with the review since you guys requested one before already you can ask for a second opinion review from [this form](https://airtable.com/shrQAqnBwek5a0O0s). thank you

**Review by nicupop729 — COMMENTED** [review]
Hello @Fayob, @Okechukwu-muokwugwo & @AzizRAA  👋,

_This is an additional review as a result of the second opinion request._

Glad to see a great team of 3 students collaborating! :clap:
You are doing great! :1st_place_medal: 

Please find here a [link to an activity](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/how_to_ask_for_a_code_review.md) from our first week at Microverse.

There is stated with bold letters: **Remember to use the same pull request as in your initial review.**

So in order to receive the next review, please use the PR link you used for the first review.

After you implement the requested changes by your code reviewer, @ichala, you can ask again for another review in the dashboard. :+1: 

Keep rocking 🚀!

**Pull request closed without merging**
